#import "style.typ": paper, references
#show: paper.with(
  kind: "Research Essay",
  title: "What Did Congress Protect?",
  subtitle: "NSF Funding and the Limits of a Budget Rescue",
  date: "October 5, 2026",
)
#set heading(numbering: n => str(n - 1))

= The question behind the rescue
Federal support paid for approximately 56% of academic basic research in the United States in 2023 @nsb2025. Decisions in Washington therefore reach well into the universities where research is done. In 2025, the National Science Foundation (NSF) listed more than 1,600 terminated awards as of June 5, citing changed agency priorities @gaonsf2025[appendix IV]. These decisions interrupted support that had already been approved, putting continuity at issue alongside the size of future budgets.

Peer-reviewed research gives Congress a reason to take that continuity seriously. Studying earlier delays in National Institutes of Health (NIH) grant renewals, #cite(<tham2026>, form: "prose") estimate that interruptions of at least 30 days increased nonemployment by three percentage points among personnel in laboratories supported by a single R01 grant. The study concerns NIH renewals, while the NSF episode concerns terminations. Its employment finding explains why the timing and reliability of public support deserve attention: a gap in funding can reach into a researcher's career.

Congress's rejection of most proposed FY2026 science cuts was consequently worth celebrating. It was also an incomplete answer to the funding problem. I argue that Congress protected NSF against the president's proposed contraction while leaving it with less purchasing power than a decade earlier and substantially less funding than Congress had authorized for expansion. Assessing congressional protection requires those comparisons alongside the presidential request. Otherwise, the severity of the president's proposal sets the standard for what counts as success.

NSF is the principal case in this essay. Its FY2017–FY2026 funding record makes it possible to distinguish a successful budget negotiation from sustained financial support. NASA's spending priorities provide a brief comparison, and NSF's grant terminations show why appropriations must be followed into agency decisions. As a physics student working in cosmology, I want public funding to sustain the researchers who turn observations into measurements. That requires asking what the money Congress preserves can actually support.

= What Congress saved
The course's treatment of Congress distinguishes its budgetary function from its oversight of the executive branch @coursecongress2026[secs.~6.5.2–6.5.3]. Article I's Appropriations Clause grounds Congress's spending power: Treasury withdrawals require appropriations made by law @constitution. The president proposes a budget, Congress supplies budget authority, and agencies use that authority to incur obligations and make payments. An appropriation therefore establishes resources agencies may use; its passage is an exercise of legislative power rather than approval of a presidential decision already made.

For FY2026, the president requested approximately \$3.903 billion for NSF, compared with \$9.060 billion enacted for FY2025 @harris2026[table 1]. Congress instead provided \$8.750 billion in the law signed on January 23, 2026 @congress2026. Calculated against the FY2025 enacted baseline, the request would have reduced funding by 56.9%; the final appropriation reduced it by 3.4%. Congress offset approximately 94.0% of the proposed reduction. That was a substantial check on the administration's budget agenda, leaving NSF with nearly \$4.85 billion more than the president had requested.

The comparison becomes more favorable to Congress when it uses the amount actually available in FY2025. The enacted total included \$234 million in emergency construction funding that the president did not make available, leaving an adjusted baseline of \$8.826 billion @harris2026[pp.~2–4]. Relative to that amount, FY2026 funding fell by only 0.9%. Congress preserved nearly the previous year's nominal resources. Recognizing that achievement is necessary to assess its limits fairly.

The public arguments for the settlement reflected different political commitments. Senators Susan Collins and Jerry Moran emphasized competitiveness and benefits to constituents, while Senator Patty Murray emphasized resisting the administration's cuts @senate2026 @murray2026. Both positions gave legislators reasons to oppose the request. Neither, by itself, answers how the surviving appropriation compares with NSF's longer-term needs. For that question, the president's proposed number is too movable a reference point.

= A decade of purchasing power
@fig-gap illustrates the problem. Appropriations exceeded the president's request in every fiscal year from 2018 through 2021; they fell below the request in every year from 2022 through 2025 @harris2026[table A-1]. A comparison with the request describes the outcome of a particular budget contest. The underlying funding record needs a measure that remains meaningful when the administration's ambitions change.

I assembled ten fiscal years of NSF funding from Congressional Research Service (CRS) tables and the FY2026 appropriations law. The series records budget authority, including the historical adjustments reported by CRS. To compare purchasing power, I converted the amounts to FY2025 dollars using the GDP price index published in the FY2027 historical tables by the #cite(<ombdeflators2026>, form: "prose"). This follows CRS's use of GDP deflation, with an updated index @harris2026[table A-1]. It measures broad purchasing power across a budget that supports research, facilities, education, and administration; program-level decisions determine how that purchasing power is distributed.

NSF's nominal appropriation rose from \$7.472 billion in FY2017 to \$8.750 billion in FY2026, an increase of 17.1%. After adjustment, the same amounts are approximately \$9.61 billion and \$8.50 billion in FY2025 dollars, a decline of 11.5%. OMB marks the FY2026 price index as an estimate. The result through FY2025 already shows a 5.7% real decline from FY2017, so the finding of erosion predates that estimated endpoint. Congress's recent defense preserved a budget whose purchasing power had already weakened.

#figure(
  image("figures/funding_gap.pdf", width: 100%, alt: "NSF requested, appropriated, and authorized funding in nominal dollars, and inflation-adjusted appropriations, FY2017 through FY2026."),
  placement: none,
  caption: [
    NSF funding, FY2017–FY2026. (a) Nominal requests, appropriations, and CHIPS and Science Act authorizations; authorizations are not funds available to spend. (b) Appropriations in FY2025 dollars, using OMB's GDP price index. The open FY2026 circle and dotted segment use an estimated deflator. Open squares show FY2023 without the supplemental appropriation and FY2025 without the unavailable \$234 million in emergency funding. Sources: #cite(<harris2026>, form: "prose", supplement: [table A-1]), #cite(<congress2026>, form: "prose"), and #cite(<ombdeflators2026>, form: "prose").
  ],
) <fig-gap>

The path was uneven. Real funding rose early in the period, and FY2023 included a supplemental appropriation; the figure also shows that year's baseline without the supplement. Those changes matter because a comparison beginning at a temporary peak would describe a different problem. Starting in FY2017 establishes a more demanding result: nominal growth over the ten-year window still failed to keep pace with general price increases. Holding NSF near last year's nominal amount could slow an immediate contraction while allowing this longer erosion to continue.

= The expansion Congress did not fund
Congress had also set a more ambitious objective. The CHIPS and Science Act authorized rising NSF funding for FY2023–FY2027 @chips2022[sec.~10303]. For FY2026, its authorization was approximately \$17.832 billion. The \$8.750 billion appropriation supplied 49.1% of that amount, leaving a \$9.082 billion gap from the authorized level. This is a comparison with Congress's own legislation, rather than a funding level proposed by scientists or by an opposing administration.

The distinction between authorization and appropriation is essential to the argument. The act established a plan for expansion, not a guarantee that NSF would receive every authorized dollar. Its goals also extended beyond maintaining existing basic research, including technology transfer and the Technology, Innovation, and Partnerships Directorate @harris2026[pp.~16–18]. The gap therefore represents expansion Congress endorsed but did not finance at the authorized scale. It calls for an explanation of which objectives legislators still intend to pursue with the smaller appropriation.

This discrepancy began before Trump's second administration: the FY2023 and FY2024 appropriations already fell below the authorized path. Congress's role in the funding problem cannot be reduced to resistance against one president. A later example reinforces the point. The House Appropriations Committee's May 2026 draft recommended \$7 billion for NSF in FY2027, 20% below FY2026 @house2026[p.~107]. That dated proposal shows how congressional opposition to a more severe cut can coexist with a willingness to reduce research funding. A legislator claiming to protect NSF should have to explain both the cut prevented and the program the resulting budget would sustain.

= A legitimate choice to spend less?
The strongest objection is that neither an earlier budget nor an authorization should bind Congress to permanent funding increases. Public money has competing uses. CRS explicitly places support for basic research alongside concerns about the broader federal budget and the option of concentrating resources in selected fields @harris2026[p.~18]. Lawmakers may reasonably prefer a smaller program, decide that an expansion was overambitious, or believe that different research priorities would produce greater public benefits. Researchers' reliance on funding gives them a stake in that choice, not the right to settle it.

I accept that discretion. An inflation-adjusted baseline is a standard for explaining a decision, not an automatic entitlement to more money. My objection is to presenting successful resistance to the president as a sufficient account of what Congress has protected. If legislators judge NSF's authorized growth to be unaffordable or unwise, they should identify the goals they are scaling back. If efficiency is supposed to absorb the reduction, they should explain what will become less costly and how research commitments will be met. This preserves elected officials' authority while making their claim of protection open to evaluation.

NASA shows why that explanation must also reach below agency totals. In the accounts examined here, Science funding declined by about 4.9% in real terms from FY2017 to FY2026, while Exploration rose by 36.0% (@fig-nasa). Both estimates use the same GDP adjustment as the NSF analysis. The FY2027 request would reduce Science by 46.3% from FY2026 and increase Exploration by 9.4%. For an astrophysicist, a defense of NASA's overall budget leaves an obvious question: how much support is being preserved for investigating the universe?

#figure(
  image("figures/nasa_priorities.pdf", width: 100%, alt: "NASA Science and Exploration funding in FY2025 dollars over FY2017 through FY2026, beside proposed FY2027 percentage changes across NASA accounts and science divisions."),
  placement: none,
  caption: [
    NASA funding and proposed priorities. (a) Science and Exploration budget authority in FY2025 dollars. Historical values include the adjustments reported by CRS; FY2024–FY2026 are enacted amounts. Open FY2026 markers use OMB's estimated deflator. Biological and physical sciences moved into Science around FY2021; the account totals retain that transfer. (b) FY2027 requests relative to FY2026 enacted funding; the five rows below the divider are Science divisions, using congressional allocations as baselines. Nested categories must not be summed. Separate multiyear mandatory funding is excluded. Sources: #cite(<morgan2019>, form: "prose"), #cite(<morganlindbergh2024>, form: "prose"), #cite(<nasa2026>, form: "prose", supplement: [p.~BUD-1]), #cite(<appropriators2026>, form: "prose", supplement: [pp.~52–53]), and #cite(<ombdeflators2026>, form: "prose").
  ],
) <fig-nasa>

Human exploration has purposes that elected officials may value, and NASA's account totals include changes in the activities they fund. The #cite(<omb2026>, form: "prose", supplement: [pp.~67–69]) also points to particular cost concerns, including Mars Sample Return's escalation, in defending the administration's priorities. Congress should weigh those arguments against the scientific work a redirection would displace. Congress should likewise name the NSF objectives it intends to protect and explain how the appropriation will support them. That would connect a claim about the budget to a decision about the research.

= Following the appropriation into research
NSF's 2025 terminations make that requirement concrete. The agency changed its treatment of broader impacts, the expected benefits of research beyond new knowledge. Following a preliminary injunction, it reinstated 114 awards to 45 institutions in June @nsfpriorities2025. Previously approved support was interrupted and then restored in this episode. A favorable agency-wide appropriation would not, on its own, tell Congress whether such a project could continue. That is where the oversight function discussed in the course becomes necessary.

The research on funding delays supplies a reason to ask about timing as well as totals. #cite(<tham2023>, form: "prose") finds that interrupted NIH renewals disrupt laboratory spending and that additional grants help laboratories absorb the interruption. Its publication estimates are not statistically distinguishable from zero; its clearest result concerns the resources available to keep work going. The employment findings of #cite(<tham2026>, form: "prose") extend that concern to careers. For NSF oversight, these studies support asking which teams have little alternative funding and how long they must wait when support is interrupted. Answering those questions would connect a preserved appropriation to the people it is meant to support.

I would make that connection part of Congress's explanation of its NSF funding decisions. Appropriators should compare the chosen amount with the president's request, an inflation-adjusted historical baseline, and the relevant authorized goals, then identify the activities they expect the agency to sustain or reduce. NSF's spending plans and subsequent reporting should make departures from those expectations visible, including terminations and reinstatements of awards. Congress already requires spending plans in the FY2026 funding framework @congress2026[sec.~528] @appropriators2026[pp.~1–3]. Committees can use them to question agency officials about the work supported by the appropriation and require explanations when implementation departs from the stated plan.

This would also give scientific advocates a more useful basis for approaching lawmakers. The American Astronomical Society encouraged members to thank Congress for the FY2026 settlement @aas2026, an example of the constituent mobilization discussed in the course @coursecongress2026[sec.~6.6.4]. The next request should be more specific: which research commitments will this funding sustain, and which will it put aside? Public answers would let researchers challenge an agency's decision or a legislator's priorities without treating every budget reduction as equally damaging.

= Conclusion
Congress's FY2026 NSF appropriation was a real use of its power of the purse. It prevented most of a proposed reduction that would have transformed the agency's funding. Yet the ten-year record shows why that success cannot carry the whole argument for congressional protection: purchasing power declined, and Congress did not finance its expansion plan at the authorized scale. I would judge Congress by whether it makes those choices explicit and follows the resulting resources into the research it says it supports. Congress can choose a smaller scientific program. It should then defend that choice in terms of the work Americans will be able to pursue, rather than relying on the larger cut it rejected.

#pagebreak()
#references(title: "References")
