#import "style.typ": paper, references
#show: paper.with(
  kind: "Research Essay",
  title: "What Did Congress Protect?",
  subtitle: "NSF Funding and the Limits of a Budget Rescue",
  date: "October 5, 2026",
)
#set heading(numbering: (n1, ..x) => numbering("1.a", n1 - 1, ..x))

= The question behind the rescue
Federal support paid for approximately 56% of academic basic research in the United States in 2023 @nsb2025. Decisions in Washington therefore reach well into the universities where research is done. In 2025, the National Science Foundation (NSF) listed more than 1,600 terminated awards as of June 5, citing changed agency priorities @gaonsf2025[appendix IV]. These decisions interrupted support that had already been approved, putting continuity at issue alongside the size of future budgets. As a physics student working in cosmology, I have a stake in whether federal commitments last long enough for researchers to carry out their work.

Peer-reviewed research gives Congress a reason to take that continuity seriously. Studying earlier delays in National Institutes of Health (NIH) grant renewals, #cite(<tham2026>, form: "prose", supplement: [abstract]) estimate that interruptions of at least 30 days increased nonemployment by three percentage points among personnel in laboratories supported by a single R01 grant. The study concerns NIH renewals, while the NSF episode concerns terminations. Its employment finding explains why the timing and reliability of public support deserve attention: a gap in funding can reach into a researcher's career.

I argue that Congress should justify NSF funding in terms of the research objectives it intends to sustain, then require public reporting and 30 days’ notice before category-wide grant cancellations. A statutory bar on implementing those cancellations during the notice period would give Congress time to examine the decision and affected teams time to seek alternative support. The FY2026 settlement protected NSF against most of the president's proposed contraction, yet left it with less purchasing power than a decade earlier and substantially less funding than Congress had authorized for expansion. A successful budget negotiation is therefore an inadequate standard of protection: it lets the severity of the president's proposal define success.

NSF is the principal case, examined over FY2017–FY2026. NASA provides a brief comparison of priorities within an agency, while the grant terminations expose the difference between allocating money and overseeing its use. The policy question is how Congress can make a claim of protection answerable to the research it says it supports.

= What Congress saved
The course's treatment of Congress distinguishes its budgetary function from its oversight of the executive branch @coursecongress2026[secs.~6.5.2–6.5.3]. Article I's Appropriations Clause grounds Congress's spending power: Treasury withdrawals require appropriations made by law @constitution. The president proposes a budget, Congress supplies budget authority, and agencies use that authority to incur obligations and make payments. An appropriation therefore establishes resources agencies may use; its passage is an exercise of legislative power rather than approval of a presidential decision already made.

For FY2026, the president requested approximately \$3.903 billion for NSF, compared with \$9.060 billion enacted for FY2025 @harris2026[table 1]. Congress instead provided \$8.750 billion in the law signed on January 23, 2026 @congress2026. Calculated against the FY2025 enacted baseline, the request would have reduced funding by 56.9%; the final appropriation reduced it by 3.4%. Congress offset approximately 94.0% of the proposed reduction. That was a substantial check on the administration's budget agenda, leaving NSF with nearly \$4.85 billion more than the president had requested.

The comparison becomes more favorable to Congress when it uses the amount actually available in FY2025. The enacted total included \$234 million in emergency construction funding that the president did not make available, leaving an adjusted baseline of \$8.826 billion @harris2026[pp.~2–4]. Relative to that amount, FY2026 funding fell by only 0.9%. Congress preserved nearly the previous year's nominal resources. Recognizing that achievement is necessary to assess its limits fairly.

The public arguments for the settlement reflected different political commitments. Senators Susan Collins and Jerry Moran emphasized competitiveness and benefits to constituents, while Senator Patty Murray emphasized resisting the administration's cuts @senate2026 @murray2026. Both positions gave legislators reasons to oppose the request. Neither, by itself, answers how the surviving appropriation compares with NSF's needs over the longer term. For that question, the president's proposed number is too movable a reference point.

= A decade of purchasing power
@fig-gap illustrates the problem. Appropriations exceeded the president's request in every fiscal year from 2018 through 2021; they fell below the request in every year from 2022 through 2025 @harris2026[table A-1]. A comparison with the request describes the outcome of a particular budget contest. The underlying funding record needs a measure that remains meaningful when the administration's ambitions change.

I assembled ten fiscal years of NSF funding from Congressional Research Service (CRS) tables and the FY2026 appropriations law. The series records budget authority, including the historical adjustments reported by CRS. To compare purchasing power, I converted the amounts to FY2025 dollars using the GDP price index published in the FY2027 historical tables by the #cite(<ombdeflators2026>, form: "prose"). This follows CRS's use of GDP deflation, with an updated index @harris2026[table A-1]. The GDP index measures general price changes; the salaries, equipment, and facilities in NSF-funded research may have a different cost trajectory. I use it to compare broad budget purchasing power, while an estimate of research-specific capacity would require costs matched to NSF's portfolio.

NSF's nominal appropriation rose from \$7.472 billion in FY2017 to \$8.750 billion in FY2026, an increase of 17.1%. After adjustment, the same amounts are approximately \$9.606 billion and \$8.501 billion in FY2025 dollars, a decline of 11.5%. All percentage changes use unrounded values. OMB marks the FY2026 price index as an estimate. The result through FY2025 already shows a 5.7% real decline from FY2017, so the finding of erosion predates that estimated endpoint. For FY2025 the main series retains the enacted \$9.060 billion, while the open square excludes the unavailable emergency funding. Retaining the larger amount makes the 5.7% decline conservative: on the \$8.826 billion available baseline used above, the decline is 8.1%. Congress's recent defense preserved a budget whose purchasing power had already weakened.

#figure(
  image(
    "figures/funding_gap.pdf",
    width: 100%,
    alt: "NSF requested, appropriated, and authorized funding in nominal dollars, and inflation-adjusted appropriations, FY2017 through FY2026.",
  ),
  placement: none,
  caption: [
    NSF funding, FY2017–FY2026. (a) Nominal requests, appropriations, and CHIPS and Science Act authorizations; authorizations are not funds available to spend. (b) Appropriations in FY2025 dollars, using OMB's GDP price index. The open FY2026 circle and dotted segment use an estimated deflator. Open squares show FY2023 without the supplemental appropriation and FY2025 without the unavailable \$234 million in emergency funding. Sources: #cite(<harris2026>, form: "prose", supplement: [table A-1]), #cite(<congress2026>, form: "prose"), and #cite(<ombdeflators2026>, form: "prose").
  ],
) <fig-gap>

The path was uneven. Real funding rose early in the period, and FY2023 included a supplemental appropriation; the figure also shows that year's baseline without the supplement. Those changes matter because a comparison beginning at a temporary peak would describe a different problem. Starting in FY2017 avoids making that peak the standard. The inflation surge in 2021–2023 also contributed to the erosion: prices can reduce a budget's purchasing power without Congress voting for a nominal cut. Congress then faces a choice about whether to compensate for those costs. Holding NSF near last year's dollar amount can prevent an immediate contraction while leaving that question unresolved.

= The expansion Congress did not fund
Congress had also set a more ambitious objective. The CHIPS and Science Act authorized rising NSF funding for FY2023–FY2027 @chips2022[sec.~10303]. For FY2026, its authorization was approximately \$17.832 billion. The \$8.750 billion appropriation supplied 49.1% of that amount, leaving a \$9.082 billion gap from the authorized level. This is a comparison with Congress's own legislation, rather than a funding level proposed by scientists or by an opposing administration.

The distinction between authorization and appropriation is essential to the argument. The act established a plan for expansion, not a guarantee that NSF would receive every authorized dollar. Its goals also extended beyond maintaining existing basic research, including technology transfer and the Technology, Innovation, and Partnerships Directorate @harris2026[pp.~16–18]. The gap therefore represents expansion Congress endorsed but did not finance at the authorized scale. Congress's authorized objectives and its funded program had diverged before the confrontation over the FY2026 request.

The FY2023 and FY2024 shortfalls predate the current administration, so Congress's role cannot be reduced to resistance against one president.

= A legitimate choice to spend less?
Congress's own recent choices show that spending less is a live option: the House Appropriations Committee's May 2026 draft recommended \$7 billion for NSF in FY2027, 20% below FY2026 @house2026[p.~107]. This was a proposed congressional reduction, not an enacted cut. As of October 5, FY2027 has begun under the continuing resolution signed on September 2, which generally extends FY2026 funding rates through December 11 unless superseded by appropriations legislation @cr2027[division A, secs.~101, 106]. Temporary continuation postpones the full-year decision; the May draft remains evidence of the choices under consideration, rather than NSF's operating appropriation.

The strongest objection is that neither an earlier budget nor an authorization should bind Congress to permanent funding increases. Public money has competing uses. CRS explicitly places support for basic research alongside concerns about the broader federal budget and the option of concentrating resources in selected fields @harris2026[p.~18]. Lawmakers may reasonably prefer a smaller program, decide that an expansion was overambitious, or believe that different research priorities would produce greater public benefits. Researchers' reliance on funding gives them a stake in that choice, not the right to settle it.

I accept that discretion. An inflation-adjusted baseline is a standard for explaining a decision, not an automatic entitlement to more money. Nor does the authorization gap establish that every proposed expansion deserved funding. The objection would defeat an argument for automatic budget restoration. It does not excuse calling a settlement protective without accounting for the work it can sustain.

NASA makes that distinction visible below the agency level. Science funding declined by about 4.9% in real terms from FY2017 to FY2026, while Exploration rose by 36.0% (@fig-nasa). Both estimates use the same GDP adjustment as the NSF analysis. The comparison describes the funded program that emerged from appropriations and subsequent adjustments; it does not isolate Congress's preferences from those of the executive. Its value here is to show how differently activities within one agency can fare. The FY2021 shift of biological and physical sciences funding into Science also enlarges the later account @morganlindbergh2024[p.~2, note c]. Retaining that addition understates the decline for the activities already included in Science in FY2017. For NSF, a protected agency total could likewise accommodate quite different choices about fields, facilities, and researchers.

#figure(
  image(
    "figures/nasa_priorities.pdf",
    width: 82%,
    alt: "NASA Science and Exploration budget authority in FY2025 dollars from FY2017 through FY2026.",
  ),
  placement: none,
  caption: [
    NASA Science and Exploration funding, FY2017–FY2026, in FY2025 dollars. Historical values include CRS's reported adjustments; FY2024–FY2026 are enacted amounts. Open FY2026 markers use OMB's estimated deflator. Biological and physical sciences moved into Science around FY2021; the totals retain that transfer, so they are not a constant-program comparison. Separate multiyear mandatory funding is excluded. Sources: #cite(<morgan2019>, form: "prose"), #cite(<morganlindbergh2024>, form: "prose"), #cite(<nasa2026>, form: "prose", supplement: [p.~BUD-1]), and #cite(<ombdeflators2026>, form: "prose").
  ],
) <fig-nasa>

Human exploration has purposes that elected officials may reasonably value. The different trajectories show why preserving an agency's total is too imprecise a claim: the activities funded determine which public purposes survive. The same question applies to NSF.

= Following the appropriation into research
NSF's 2025 terminations expose a second problem: the executive branch can change the research program after Congress funds it. Following a preliminary injunction, NSF reinstated 114 awards to 45 institutions in June @nsfpriorities2025. That was a limited set of restorations, far smaller than the more than 1,600 terminations reported earlier; it does not establish the eventual status of the remaining awards. A larger appropriation alone would not have prevented those executive decisions. The problem concerns control over implementation as well as the amount appropriated.

This is the practical significance of the course's distinction between budgeting and oversight @coursecongress2026[secs.~6.5.2–6.5.3]. Congress delegates funding decisions to an agency with scientific expertise, but agency officials possess information about individual awards that legislators cannot obtain from the topline budget. Executive priorities may also diverge from the program Congress intended to fund. This is a principal-agent problem: legislators delegate decisions but cannot readily observe whether the agency is carrying out their purposes. Oversight addresses that gap by tracing what the agency actually does with its authority. Researchers' reports of interrupted work can therefore matter even when the agency's nominal budget appears protected.

The Impoundment Control Act (ICA) provides an existing legal check on withholding budget authority. In August 2025, GAO concluded that NIH had violated it by withholding appropriated funds from obligation and expenditure without following the act's procedures @gao2025. That decision concerned NIH, not a ruling on every NSF termination. GAO also distinguishes unlawful withholding from permissible delays in carrying out a program. An individual award's cancellation and an agency's refusal to use appropriated resources raise different questions. Congress needs records of both award decisions and unspent balances to determine whether its funded program is being carried out.

The studies of funding interruptions explain why that inquiry needs to reach beyond annual totals. #cite(<tham2023>, form: "prose") finds that interrupted NIH renewals disrupt laboratory spending and that additional grants help laboratories absorb the interruption. The estimated effect on the number of papers produced was not statistically distinguishable from zero. Spending and staffing continuity can therefore reveal disruption that a publication count misses. Alongside the career effects reported by #cite(<tham2026>, form: "prose"), this supports monitoring how long research teams wait for support, especially when they have little alternative funding.

= Public reporting and advance notice
Congress already requires more than an agency total. Section 528 of the FY2026 act requires NSF to submit a spending plan within 45 days. The explanatory statement limits reductions to individual research directorates and specifies support for facilities, including astronomy priorities @congress2026[sec.~528] @appropriators2026[pp.~61–62]. My proposal would extend these requirements into a recurring public comparison of planned support with implementation. Before approving an appropriation, legislators should publish its relationship to the presidential request, historical purchasing power, and authorized objectives, identifying which commitments they are sustaining or reducing. NSF's 45-day plan should use those same program categories, then quarterly reports should reconcile planned funding with obligations, unobligated balances, and award terminations or reinstatements, giving the dates, reasons, and amounts involved.

Congress should put those reporting duties and deadlines in the enacted appropriations text. I would also require 30 days' notice to Congress and the public before NSF implements category-wide grant cancellations based on changed policy priorities. By category-wide, I mean cancellations under a common policy directive that targets awards by program, research subject, or recipient class, even if NSF issues the termination notices separately. The rule would exclude decisions based on an individual award's scientific performance and allow exceptions for fraud, immediate safety risks, or a controlling legal requirement. A statutory bar on implementing covered cancellations during the notice period would give the requirement force. Advance notice would give affected teams time to seek bridge funding before support stops, creating an opportunity to avoid the interruptions linked to job losses and laboratory disruption in the NIH studies @tham2023 @tham2026. Those findings support time to prepare; choosing 30 days as the minimum notice period is a policy judgment. Committees could question NSF officials and seek GAO review of possible withholding before teams lose support; changing the underlying law would still require legislative action.

An administration could object that the waiting period intrudes on executive management and delays a lawful change in priorities. That friction is real. I would accept a short delay for a policy that withdraws support across a class of existing awards, while leaving individual performance decisions and urgent exceptions outside the rule. The bar would expire automatically after 30 days, without requiring a committee's permission: NSF could then proceed if the cancellations were otherwise lawful. This design gives Congress time to scrutinize implementation without giving its committees a continuing veto over agency decisions.

Reporting alone cannot make legislators use their oversight powers. Scientific organizations can help supply the pressure. The American Astronomical Society encouraged members to thank Congress for the FY2026 settlement @aas2026. The course describes interest groups supplying research and mobilizing constituents @coursecongress2026[sec.~6.6.4]; public records would let those groups connect a local laboratory's interruption to an agency decision and a funded congressional commitment. The resulting question to a representative would be concrete: is this the program Congress intended to preserve?

= Conclusion
Congress protected most of NSF's previous nominal funding in FY2026. It did not restore earlier purchasing power or finance expansion at the authorized scale, and the appropriation alone could not secure continuity for individual awards. Rejecting the president's deepest cuts was a substantial exercise of the power of the purse. Calling it sufficient protection, however, lets a movable presidential request stand in for an account of what public research can do. The case for stronger reporting and notice requirements follows from the distance between the budget Congress approves and the decisions that reach laboratories. Congress can choose a smaller scientific program. It should make that choice in public and remain accountable for whether the executive carries it out.

#pagebreak()
#references(title: "References")
